/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Cayman.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Cayman(props) {
  const { nodes, materials } = useGLTF('models/Cayman.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }



  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 || overlay==34 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.alcantara_01_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_02_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_03_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_04_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_05_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_06_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_07_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_08_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_09_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_10_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_11_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_12_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_13_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_14_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.alcantara_15_alcantara_0.geometry} material={materials.alcantara} />
      <mesh geometry={nodes.black_01_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_02_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_03_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_04_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_05_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_06_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_07_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_08_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_09_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_10_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_11_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_12_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_13_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_14_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_15_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_16_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_17_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_18_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_19_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_20_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_21_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_22_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_23_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_24_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_25_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_26_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.black_matt_02_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_03_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_04_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_04_black_matt_0001.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_05_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_05_black_matt_0001.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_05_black_matt_0002.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_07_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_08_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_09_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_10_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_11_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_12_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_13_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_14_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_15_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_16_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_17_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_18_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_19_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_20_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_21_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_22_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_23_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_24_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_25_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_26_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_27_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_28_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_29_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_30_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_31_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_32_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_33_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_34_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_35_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_36_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_37_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_38_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_39_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_40_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_41_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_42_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_43_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_44_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_45_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_46_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_47_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_48_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_49_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_50_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_51_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_52_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_53_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_54_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_55_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_56_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_57_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_58_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_59_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_60_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_61_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_62_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_63_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_64_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_65_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_66_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_67_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_68_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_69_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_70_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_71_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_72_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_73_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_74_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_75_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_76_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_77_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_78_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_79_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_80_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_81_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_82_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_83_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_84_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_85_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_86_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_87_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_88_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_89_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_90_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_91_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_92_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_93_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_94_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_95_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_96_black_matt_0.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_normal_bump_01_black_matt_normal_bump_0.geometry} material={materials.black_matt_normal_bump} />
      <mesh geometry={nodes.black_shiny_02_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_03_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_04_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_05_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_06_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_07_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_08_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_09_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_10_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_11_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_12_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_13_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_14_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_15_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_16_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_17_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_18_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_19_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_20_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_21_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_22_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_23_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_24_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_25_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_26_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_27_black_shiny_0.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_bump_01_black_shiny_bump_0.geometry} material={materials.black_shiny_bump} />
      <mesh geometry={nodes.body_08_body_0.geometry} material={materials.body} />
      
      <mesh geometry={nodes.body_12_body_0.geometry} material={materials.body} />
      <mesh geometry={nodes.body_15_body_0.geometry} material={materials.body} />
      <mesh geometry={nodes.body_16_body_0.geometry} material={materials.body} />
      <mesh geometry={nodes.body_normal_bump_01_body_normal_bump_0.geometry} material={materials.body_normal_bump} />
      <mesh geometry={nodes.brakes3_01_brakes3_0.geometry} material={materials.brakes3} />
      <mesh geometry={nodes.brakes3_02_brakes3_0.geometry} material={materials.brakes3} />
      <mesh geometry={nodes.brakes3_03_brakes3_0.geometry} material={materials.brakes3} />
      <mesh geometry={nodes.brakes3_04_brakes3_0.geometry} material={materials.brakes3} />
      <mesh geometry={nodes.calipers_01_calipers_0.geometry} material={materials.calipers} />
      <mesh geometry={nodes.calipers_02_calipers_0.geometry} material={materials.calipers} />
      <mesh geometry={nodes.calipers_03_calipers_0.geometry} material={materials.calipers} />
      <mesh geometry={nodes.calipers_04_calipers_0.geometry} material={materials.calipers} />
      <mesh geometry={nodes.carbon_01_carbon_0.geometry} material={materials.carbon} />
      <mesh geometry={nodes.carbon_02_carbon_0.geometry} material={materials.carbon} />
      <mesh geometry={nodes.carbon_03_carbon_0.geometry} material={materials.carbon} />
      <mesh geometry={nodes.carbon_04_carbon_0.geometry} material={materials.carbon} />
      <mesh geometry={nodes.chrome_01_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_02_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_03_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_04_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_05_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_06_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_07_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_08_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_09_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_10_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_11_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_12_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_13_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_14_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_15_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_16_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_17_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_18_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_19_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_20_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_21_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_22_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_23_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_24_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_25_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_26_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_27_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_28_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_29_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_30_chrome_0.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_d_01_chrome_d_0.geometry} material={materials.chrome_d} />
      <mesh geometry={nodes.chrome_d_02_chrome_d_0.geometry} material={materials.chrome_d} />
      <mesh geometry={nodes.chrome_d_bump_01_chrome_d_bump_0.geometry} material={materials.chrome_d_bump} />
      <mesh geometry={nodes.chrome_red_bump_01_chrome_red_bump_0.geometry} material={materials.chrome_red_bump} />
      <mesh geometry={nodes.chrome_red_bump_02_chrome_red_bump_0.geometry} material={materials.chrome_red_bump} />
      <mesh geometry={nodes.d_glass_01_d_glass_0.geometry} material={materials.d_glass} />
      <mesh geometry={nodes.d_glass_02_d_glass_0.geometry} material={materials.d_glass} />
      <mesh geometry={nodes.d_glass_03_d_glass_0.geometry} material={materials.d_glass} />
      <mesh geometry={nodes.display_01_display_0.geometry} material={materials.display} />
      <mesh geometry={nodes.gauges_01_gauges_0.geometry} material={materials.gauges} />
      <mesh geometry={nodes.glass_01_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_01_glass_0001.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_02_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_03_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_04_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_05_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_06_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_07_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_08_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_09_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_10_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.gold_01_gold_0.geometry} material={materials.gold} />
      <mesh geometry={nodes.interior_01_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_02_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_03_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_04_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_05_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_06_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_07_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_08_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_09_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_10_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_11_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_12_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_13_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_14_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_15_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_16_interior_0.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_red_01_interior_red_0.geometry} material={materials.interior_red} />
      <mesh geometry={nodes.interior_yellow_01_interior_yellow_0.geometry} material={materials.interior_yellow} />
      <mesh geometry={nodes.interior_yellow_02_interior_yellow_0.geometry} material={materials.interior_yellow} />
      <mesh geometry={nodes.interior_yellow_03_interior_yellow_0.geometry} material={materials.interior_yellow} />
      <mesh geometry={nodes.leather_01_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_02_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_03_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_04_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_05_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_06_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_07_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_08_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_09_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_10_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_11_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_12_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_13_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_14_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_15_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_16_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_17_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_18_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_19_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_20_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_21_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_22_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_23_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_24_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_25_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_26_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_27_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_28_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_29_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_30_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_31_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_32_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_33_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_34_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_35_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_36_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_37_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_38_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_39_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_40_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.leather_41_leather_0.geometry} material={materials.leather} />
      <mesh geometry={nodes.lights_glass_01_lights_glass_0.geometry} material={materials.lights_glass} />
      <mesh geometry={nodes.lights_glass_02_lights_glass_0.geometry} material={materials.lights_glass} />
      <mesh geometry={nodes.logo_01_logo_0.geometry} material={materials.logo} />
      <mesh geometry={nodes.plate_01_plate_0.geometry} material={materials.plate} />
      <mesh geometry={nodes.plate_02_plate_0.geometry} material={materials.plate} position={[0, 0, 0.028]} />
      <mesh geometry={nodes.r_glass_01_r_glass_0.geometry} material={materials.r_glass} />
      <mesh geometry={nodes.r_glass_bump_01_r_glass_bump_0.geometry} material={materials.r_glass_bump} />
      <mesh geometry={nodes.r_lights_01_r_lights_0.geometry} material={materials.r_lights} />
      <mesh geometry={nodes.red_01_red_0.geometry} material={materials.material} />
      <mesh geometry={nodes.red_02_red_0.geometry} material={materials.material} />
      <mesh geometry={nodes.red_03_red_0.geometry} material={materials.material} />
      <mesh geometry={nodes.red_04_red_0.geometry} material={materials.material} />
      <mesh geometry={nodes.rims_01_rims_0.geometry} material={materials.rims} />
      <mesh geometry={nodes.rims_02_rims_0.geometry} material={materials.rims} />
      <mesh geometry={nodes.rims_03_rims_0.geometry} material={materials.rims} />
      <mesh geometry={nodes.rims_04_rims_0.geometry} material={materials.rims} />
      <mesh geometry={nodes.rims_05_rims_0.geometry} material={materials.rims} />
      <mesh geometry={nodes.rims_06_rims_0.geometry} material={materials.rims} />
      <mesh geometry={nodes.rims_07_rims_0.geometry} material={materials.rims} />
      <mesh geometry={nodes.rims_08_rims_0.geometry} material={materials.rims} />
      <mesh geometry={nodes.silver_01_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_02_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_03_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_04_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_05_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_06_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_07_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_08_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_09_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_10_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_11_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_12_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_13_silver_0.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_d_01_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_02_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_03_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_04_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_05_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_06_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_07_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_08_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_09_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_10_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_11_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_12_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_13_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_14_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_15_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_16_silver_d_0.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.tire_mat5_01_tire_mat5_0.geometry} material={materials.tire_mat5} />
      <mesh geometry={nodes.tire_mat5_02_tire_mat5_0.geometry} material={materials.tire_mat5} />
      <mesh geometry={nodes.tire_mat5_03_tire_mat5_0.geometry} material={materials.tire_mat5} />
      <mesh geometry={nodes.tire_mat5_04_tire_mat5_0.geometry} material={materials.tire_mat5} />
      <mesh geometry={nodes.trunk_light_01_trunk_light_0.geometry} material={materials.trunk_light} />
      <mesh geometry={nodes.wire_mesh_01_wire_mesh_0.geometry} material={materials.wire_mesh} />
      <mesh geometry={nodes.wire_mesh_02_wire_mesh_0.geometry} material={materials.wire_mesh} />
    </group>
  )
}

useGLTF.preload('/Cayman.glb')
